version: '3.8'

services:
  db:
    platform: linux/x86_64
    image: mysql:5.7
    container_name: octo_events_db
    command: --innodb-use-native-aio=0
    restart: unless-stopped
    tty: true
    user: mysql
    volumes:
      - ~/.docker/db-data:/var/lib/mysql:rw
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: octo_events
    ports:
      - '3306:3306'
    networks:
      - octo_events_network

  nginx:
    image: nginx:alpine
    tty: true
    container_name: octo_events_nginx
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - octo_events_network

networks:
  octo_events_network:
